AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  teletenor-contralto

Parameters:
  TeletenorApiStageSecret:
    Type: String

Globals:
  Function:
    Timeout: 2

Resources:
  TeletenorLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: teletenor/
      Handler: js/main/lambda-main.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Events:
        TelegramUpdate:
          Type: Api
          Properties:
            Method: post
            Path: /update
            RestApiId: !Ref TeletenorUpdateWebhookApi
  TeletenorUpdateWebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Sub "${TeletenorApiStageSecret}Prod"


Outputs:
  TeletenorUpdateWebhookApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${TeletenorUpdateWebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${TeletenorApiStageSecret}Prod/update"
  TeletenorLambdaFunction:
    Description: "TeletenorLambdaFunction ARN"
    Value: !GetAtt TeletenorLambdaFunction.Arn
